# Generated by Django 6.0.6 on 2026-06-29 06:09

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinerprofile',
            name='faculty_id',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='examinerprofile',
            name='office_room',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='cgpa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='session',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='supervisorprofile',
            name='faculty_id',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='supervisorprofile',
            name='office_room',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[accounts.validators.validate_phone]),
        ),
    ]
